### ISSUE TITLE
Establish Display Catalogue for Customer Search

### ISSUE THREAD

**Issue by vihuynh0** [DavidMajomi/Beer-co#17]
Location: AJAX_search.php
Expected Result: A customer is easily exposed to beers they did not specifically search for.
Result: Customer is faced with a lot of white space.
Description: Developer suggested to reuse the specials page features to show the whole beer catalogue. Have it be displayed before the customer has to search for anything.

**Comment by DavidMajomi** [comment]
Resolved alongside search filter issue
