### ISSUE TITLE
Add New Special Experience

### ISSUE THREAD

**Issue by vihuynh0** [DavidMajomi/Beer-co#24]
edit_specials.php : Shows you a list of the current specials with the ability to view, update and delete
specials_crud_create.php : Shows the entire database including the specials with the ability to view, update and delete

Description: admin menu > edit specials > click green "Add New Special" I think this brings out the entire list of the database. The button is still there but does nothing (1)

For admin experience I think it is best to only show which beers aren't on special when you click the add new specials button (2).

(and if we had more time, let the admin be able to search if they wanted to add beer to the specials. Our small database is good for testing but in practice, it would be inconvenient to scroll to the beer you wanted to add)

**Comment by vihuynh0** [comment]
Just added issue 25: Deleting Beer Special Deletes From Real Database

Probably best to disable the ability to delete on
specials_crud_create.php
while you're at it

**Comment by DavidMajomi** [comment]
Resolved
