### ISSUE TITLE
Deleting Beer Special Deletes From Real Database

### ISSUE THREAD

**Issue by vihuynh0** [DavidMajomi/Beer-co#25]
edit_specials.php : Clicking the trashcan on this page correctly removes the special, prompting "Are you sure you want to remove this beer from specials?"

however...
> Upon clicking Add New Special
specials_crud_create.php : Admin is able to delete from the database. The prompt does say "Are you sure you want to **delete** this beer record?" (1). We do not want the ability to wipe out beers from specials.

Clicking Yes/No returns you to admin_index.php, but it should be back to the specials page (2).

**Comment by DavidMajomi** [comment]
Fixed
