### ISSUE TITLE
duplicate beers in the database 

### ISSUE THREAD

**Issue by Namainused** [DavidMajomi/Beer-co#9]
Bug location: in test case 5.3/use case 5
Related Requirements: Req#3, Req#4, Req#5, Req#6, Req#7, Req#8
Expected result: Database does not change and display message “Beer already exists in the database.”
Result: beer is appended into the database
Description: same beer can be create and exist in the database 
Steps to reproduce: Step1-go to edit database, Step2-select create beer, Step3-enter information of an existing beer, Step4-submit beer

**Comment by KTLR0** [comment]
there was an additional line in the startup code that kept creating the same beers again
